name = "quicksortv2-l"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Quicksortv2.L"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "Quicksortv2.L"
